name: Build & Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/regionaal-archief-rivierenland/oria-builder:latest
      options: --user root # github writes tmp files whereever it wants, and that needs root access

    permissions:
      contents: write  # Needed to push to gh-pages
    defaults:
      run:
        working-directory: /ori-a-website

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          path: .

      - name: Build site as `builder` user  # set user explictly since gh rly wants root
        run: |
          sudo -u builder make update-submodule
          sudo -u builder make -j5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: ori-a.nl
