name: Build & Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/regionaal-archief-rivierenland/oria-builder:latest
    permissions:
      contents: write  # Needed to push to gh-pages

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Build site
        run: |
          make update-submodule
          make -j5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: ori-a.nl
