name: Build & Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Needed to push to gh-pages

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc make scour ripgrep fd-find fonttools uglifyjs npm wget
          npm install -g lightningcss-cli
          wget https://github.com/wilsonzlin/minify-html/releases/download/v0.16.4/minhtml-0.16.4-x86_64-unknown-linux-gnu -O /usr/local/bin/minify-html
          chmod +x /usr/local/bin/minify-html


      - name: Build site
        run: make

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
