name: Build & deploy Docker image for building the website

on:
  push:
    paths:
      - 'buildtools/Dockerfile'
      - '.github/workflows/deploy-docker-builder.yaml'
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        run: |
          IMAGE_NAME=ghcr.io/regionaal-archief-rivierenland/oria-builder:latest
          docker build -t $IMAGE_NAME -f buildtools/Dockerfile .
          docker push $IMAGE_NAME
